# Generated by Django 6.0.2 on 2026-03-23 22:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_sector', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('denominacion_generica', models.CharField(max_length=150)),
                ('denominacion_distintiva', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=150)),
                ('rfc_fabricante', models.CharField(max_length=20)),
                ('pais_fabricacion', models.CharField(max_length=50)),
                ('num_registro_sanitario', models.CharField(max_length=50)),
                ('num_prorroga', models.CharField(default='NO APLICA', max_length=50)),
                ('codigo_barras', models.CharField(max_length=50)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vigencia', models.DateField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True, verbose_name='Número de Contrato')),
                ('dependencia', models.CharField(max_length=200, verbose_name='Dependencia / Cliente')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia')),
                ('numero_fianza', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Fianza')),
            ],
            options={
                'verbose_name': 'Contrato Maestro',
                'verbose_name_plural': '1. Contratos Maestros',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('rfc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFC')),
                ('representante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Representante Legal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('servidor_correo', models.CharField(blank=True, choices=[('smtp.gmail.com', 'Gmail'), ('smtp.office365.com', 'Outlook / Office 365')], default='smtp.gmail.com', max_length=50, null=True, verbose_name='Proveedor de Correo')),
                ('correo_remitente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Emisor (Gmail/Outlook)')),
                ('password_aplicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña de Aplicación (16 letras)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EstatusProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ADJUDICADO', 'Adjudicado'), ('PERDIDO', 'Perdido'), ('EN_PROCESO', 'En proceso')], default='EN_PROCESO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocioComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Laboratorio / Socio')),
                ('correos', models.CharField(help_text='Puedes poner varios correos separados por coma (Ej: ventas@pisa.com, dir@pisa.com)', max_length=250, verbose_name='Correos Electrónicos')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de Contacto')),
            ],
            options={
                'verbose_name': 'Socio Comercial',
                'verbose_name_plural': 'Directorio de Socios',
            },
        ),
        migrations.CreateModel(
            name='ClaveContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_neto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Neto')),
                ('cantidad_minima', models.IntegerField(verbose_name='Cantidad Mínima Asignada')),
                ('cantidad_maxima', models.IntegerField(verbose_name='Cantidad Máxima Asignada')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licitaciones.catalogomedicamento', verbose_name='Clave / Medicamento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='licitaciones.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Clave Asignada',
                'verbose_name_plural': '2. Claves por Contrato',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.empresa', verbose_name='Empresa GPHARMA'),
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_procedimiento', models.CharField(max_length=100, unique=True, verbose_name='Número de procedimiento')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha y hora de publicación')),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha y hora de apertura')),
                ('fecha_junta', models.DateTimeField(verbose_name='Fecha y hora de junta de aclaraciones')),
                ('fecha_fallo', models.DateTimeField(verbose_name='Fecha y hora del acto del Fallo')),
                ('dependencia', models.CharField(max_length=150, verbose_name='Dependencia')),
                ('url_carpeta_drive', models.URLField(blank=True, null=True, verbose_name='Enlace a Google Drive')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.empresa', verbose_name='Empresa Participante')),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.estatusprocedimiento')),
            ],
            options={
                'verbose_name': 'Licitación',
                'verbose_name_plural': 'Licitaciones',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='licitacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.licitacion', verbose_name='Viene de la Licitación'),
        ),
        migrations.CreateModel(
            name='OrdenSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_orden', models.CharField(max_length=100, verbose_name='Folio de la Orden / OPM')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha en que se recibió')),
                ('fecha_limite_entrega', models.DateField(verbose_name='Fecha Límite de Entrega')),
                ('lugar_entrega', models.CharField(max_length=250, verbose_name='Destino / Almacén de Entrega')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Piezas Solicitadas')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente de Entrega 🟡'), ('ENTREGADA', 'Entregada al 100% 🟢'), ('PARCIAL', 'Entrega Parcial 🔵'), ('DEVUELTA', 'Rechazada / Devuelta 🔴'), ('NO_ATENDIDA', 'No Atendida (Desabasto) ⚫')], default='PENDIENTE', max_length=20, verbose_name='Estatus Logístico')),
                ('motivo_incidencia', models.TextField(blank=True, help_text='Explica por qué se regresó el medicamento o por qué no se surtió.', null=True, verbose_name='Motivo (Rechazo / No Atención)')),
                ('clave_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='licitaciones.clavecontrato', verbose_name='Clave del Contrato')),
            ],
            options={
                'verbose_name': 'Orden de Suministro',
                'verbose_name_plural': '3. Órdenes de Suministro',
                'ordering': ['fecha_limite_entrega'],
            },
        ),
        migrations.CreateModel(
            name='PartidaRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partida', models.IntegerField(blank=True, null=True, verbose_name='No. Partida')),
                ('cantidad_minima', models.PositiveIntegerField()),
                ('cantidad_maxima', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('Perdida por precio', 'Perdida por precio'), ('Perdida técnicamente', 'Perdida técnicamente')], default='Pendiente', max_length=30, verbose_name='Resultado')),
                ('motivo_perdida', models.CharField(blank=True, help_text='Escribe por qué se perdió (solo si fue pérdida técnica).', max_length=255, null=True, verbose_name='Motivo Técnico')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='licitaciones.licitacion')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licitaciones.catalogomedicamento', verbose_name='Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del Check-in')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Ubicación',
                'verbose_name_plural': 'Registros de Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='RemisionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega_real', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega en Destino')),
                ('folio_remision_factura', models.CharField(max_length=100, verbose_name='Folio Remisión / Factura')),
                ('cantidad_entregada', models.IntegerField(verbose_name='Piezas Entregadas en este viaje')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote del Medicamento')),
                ('caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='licitaciones.ordensuministro', verbose_name='Orden de Suministro')),
            ],
            options={
                'verbose_name': 'Remisión Físca',
                'verbose_name_plural': '4. Remisiones de Almacén',
            },
        ),
        migrations.AddField(
            model_name='catalogomedicamento',
            name='socio_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.sociocomercial', verbose_name='Contacto para Notificaciones'),
        ),
    ]
