# Generated by Django 6.0.2 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomedicamento',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogomedicamento',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
