# Generated by Django 6.0.2 on 2026-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0002_alter_catalogomedicamento_fecha_expedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de apertura'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='fecha_fallo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del acto del Fallo'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='fecha_junta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de junta de aclaraciones'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de publicación'),
        ),
    ]
