# Generated by Django 6.0.2 on 2026-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0003_alter_licitacion_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidarequerimiento',
            name='cantidad_maxima',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='partidarequerimiento',
            name='cantidad_minima',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='partidarequerimiento',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partidarequerimiento',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
