# Generated by Django 6.0.2 on 2026-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0004_alter_partidarequerimiento_cantidad_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='url_logo',
            field=models.URLField(blank=True, help_text='Pega aquí el link directo a la imagen del logo (debe terminar en .png o .jpg). Ej: https://tudominio.com/logo_sago.png', max_length=500, null=True, verbose_name='URL del Logo (Público)'),
        ),
    ]
