# Generated by Django 6.0.2 on 2026-03-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0005_empresa_url_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clavecontrato',
            options={'verbose_name': 'Clave Asignada', 'verbose_name_plural': 'Claves del Contrato'},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_fianza',
        ),
        migrations.AlterField(
            model_name='clavecontrato',
            name='cantidad_maxima',
            field=models.IntegerField(default=0, verbose_name='Cant. Máxima'),
        ),
        migrations.AlterField(
            model_name='clavecontrato',
            name='cantidad_minima',
            field=models.IntegerField(default=0, verbose_name='Cant. Mínima'),
        ),
        migrations.AlterField(
            model_name='clavecontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='licitaciones.contrato'),
        ),
        migrations.AlterField(
            model_name='clavecontrato',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Clave / Medicamento'),
        ),
        migrations.AlterField(
            model_name='clavecontrato',
            name='precio_neto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Neto'),
        ),
        migrations.CreateModel(
            name='FianzaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANTICIPO', 'Fianza de Anticipo'), ('LICITACION', 'Fianza de Licitación'), ('CUMPLIMIENTO', 'Fianza de Cumplimiento'), ('VICIOS', 'Fianza de Vicios Ocultos / Buena Calidad'), ('OTRA', 'Otra...')], max_length=20, verbose_name='Tipo de Fianza')),
                ('numero_fianza', models.CharField(max_length=100, verbose_name='No. de Póliza / Fianza')),
                ('afianzadora', models.CharField(blank=True, help_text='Ej. Sofimex, Aserta, etc.', max_length=150, null=True, verbose_name='Aseguradora / Afianzadora')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Asegurado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fianzas', to='licitaciones.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Fianza / Garantía',
                'verbose_name_plural': 'Fianzas del Contrato',
            },
        ),
    ]
