# Generated by Django 6.0.2 on 2026-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0006_alter_clavecontrato_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacion',
            name='url_carpeta_drive',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ruta_carpeta_servidor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta en Servidor Local (Ej: V:\\REPORTES...)'),
        ),
    ]
