# Generated by Django 6.0.2 on 2026-04-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0007_remove_licitacion_url_carpeta_drive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote del Producto')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('cantidad_disponible', models.IntegerField(default=0, verbose_name='Piezas Físicas Disponibles')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso al Sistema')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Clave / Medicamento')),
            ],
            options={
                'verbose_name': 'Inventario Físico',
                'verbose_name_plural': '5. Inventarios (Stock)',
                'ordering': ['fecha_caducidad'],
            },
        ),
    ]
