# Generated by Django 6.0.2 on 2026-04-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0008_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='url_carpeta_drive',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Carpeta Drive'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='numero_procedimiento_extra',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='No. Procedimiento (Externo/Histórico)'),
        ),
    ]
