# Generated by Django 6.0.2 on 2026-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0009_licitacion_url_carpeta_drive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordensuministro',
            options={'ordering': ['fecha_limite'], 'verbose_name': 'Orden de Suministro', 'verbose_name_plural': '3. Órdenes de Suministro'},
        ),
        migrations.RenameField(
            model_name='ordensuministro',
            old_name='fecha_limite_entrega',
            new_name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='folio_orden',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='lugar_entrega',
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='cantidad_entregada',
            field=models.IntegerField(default=0, verbose_name='Cantidad Entregada (Histórica)'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='clave_medicamento_historico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave (Excel)'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='clues_destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CLUES Destino'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='descripcion_medicamento',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Medicamento'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='entidad_destino',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Entidad / Lugar de Entrega'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='nombre_unidad',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre de Unidad / Dependencia'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='numero_contrato_historico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='No. Contrato (Excel)'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='numero_orden_suministro',
            field=models.CharField(default='0000', max_length=150, verbose_name='No. Orden Suministro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social (Empresa)'),
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='cantidad_solicitada',
            field=models.IntegerField(verbose_name='Cantidad Solicitada'),
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='motivo_incidencia',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo (Rechazo / No Atención)'),
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='numero_procedimiento_extra',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='No. Procedimiento (Histórico)'),
        ),
    ]
