# Generated by Django 6.0.2 on 2026-04-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0010_alter_ordensuministro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensuministro',
            name='clave_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='licitaciones.clavecontrato', verbose_name='Clave del Contrato'),
        ),
    ]
