# Generated by Django 6.0.2 on 2026-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0011_alter_ordensuministro_clave_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensuministro',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real de entrega'),
        ),
    ]
