# Generated by Django 6.0.2 on 2026-04-14 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0012_ordensuministro_fecha_entrega_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rfc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFC')),
                ('contacto_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_ventas', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('dias_credito', models.PositiveIntegerField(default=30, verbose_name='Días de Crédito')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': '1. Catálogo de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Ej. OC-GAMS-2026-001', max_length=50, unique=True, verbose_name='Folio OC')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega_esperada', models.DateField()),
                ('estatus', models.CharField(choices=[('BORRADOR', '📝 Borrador'), ('AUTORIZADA', '✅ Autorizada (Enviada)'), ('TRANSITO', '🚚 En Tránsito'), ('RECIBIDA', '📦 Recibida en Almacén'), ('CANCELADA', '❌ Cancelada')], default='BORRADOR', max_length=20)),
                ('condiciones_pago', models.CharField(blank=True, default='Transferencia a 30 días', max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa_compradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.empresa', verbose_name='Empresa que Compra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licitaciones.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': '2. Órdenes de Compra (OC)',
            },
        ),
        migrations.CreateModel(
            name='PartidaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad (Piezas)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, help_text='Se llena al llegar al almacén', verbose_name='Pzas Recibidas')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licitaciones.catalogomedicamento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_compra', to='licitaciones.ordencompra')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
