# Generated by Django 6.0.2 on 2026-04-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0013_proveedor_ordencompra_partidacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licitaciones.sociocomercial', verbose_name='Proveedor (Socio Comercial)'),
        ),
    ]
