# Generated by Django 6.0.2 on 2026-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0014_alter_ordencompra_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='condiciones_pago',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='destino',
            field=models.CharField(default='ALMACÉN GENERAL GPHARMA', help_text='Dirección o unidad donde se recibirá el medicamento', max_length=255, verbose_name='Destino de Entrega'),
        ),
    ]
