# Generated by Django 6.0.2 on 2026-04-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0015_remove_ordencompra_condiciones_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ordenes_compra/evidencias/', verbose_name='Archivo Adjunto')),
                ('descripcion', models.CharField(help_text='Ej. Cotización del proveedor, Autorización del jefe, etc.', max_length=150, verbose_name='Descripción / Título')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='licitaciones.ordencompra')),
            ],
            options={
                'verbose_name': 'Documento de Evidencia',
                'verbose_name_plural': '📂 Documentos y Evidencias',
            },
        ),
    ]
