# Generated by Django 6.0.2 on 2026-04-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0016_documentoordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='monto_fianza',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se calcula en automático (10% del monto total).', max_digits=15, null=True, verbose_name='Monto de Fianza (10%)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='porcentaje_penalizacion_diaria',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Ej. 2.5% por día de atraso', max_digits=5, verbose_name='Penalización Diaria (%)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tope_penalizacion',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Límite de la penalización (Ej. 10%)', max_digits=5, verbose_name='Tope de Penalización (%)'),
        ),
    ]
