# Generated by Django 6.0.2 on 2026-04-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0017_contrato_monto_fianza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField(verbose_name='Piezas Físicas Recibidas')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote Impreso')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('documentacion_completa', models.BooleanField(default=True, verbose_name='¿Llegó con Remisión y Certificados Analíticos?')),
                ('ubicacion', models.CharField(help_text='¿En qué parte del almacén se guardará?', max_length=150, verbose_name='Ubicación Física (Ej. Pasillo 3, Anaquel B)')),
                ('observaciones_calidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de Calidad (Cajas maltratadas, etc.)')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Recepción')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Clave / Medicamento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.ordencompra', verbose_name='Orden de Compra Vinculada')),
            ],
            options={
                'verbose_name': 'Entrada de Almacén',
                'verbose_name_plural': '📥 Recepciones de Almacén',
            },
        ),
    ]
