# Generated by Django 6.0.2 on 2026-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0018_entradaalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaalmacen',
            name='folio_remision',
            field=models.CharField(default='S/F', help_text='Anota el número de ticket o factura de esta entrega parcial.', max_length=100, verbose_name='Folio de Remisión / Factura'),
        ),
    ]
