# Generated by Django 6.0.2 on 2026-04-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0019_entradaalmacen_folio_remision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('medicamento', 'lote', 'fecha_caducidad')},
        ),
    ]
