# Generated by Django 6.0.2 on 2026-04-15 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0020_alter_inventario_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remisionentrega',
            options={'verbose_name': 'Remisión Física', 'verbose_name_plural': '4. Remisiones de Almacén'},
        ),
        migrations.RemoveField(
            model_name='remisionentrega',
            name='fecha_entrega_real',
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='Sube aquí el acuse firmado para dar la orden por Entregada.', null=True, upload_to='logistica/evidencias/', verbose_name='PDF Remisión Sellada/Firmada'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='estatus_viaje',
            field=models.CharField(choices=[('EN_RUTA', '🚚 En Ruta hacia el Instituto'), ('ENTREGADA', '✅ Entregada y Comprobada')], default='EN_RUTA', max_length=20, verbose_name='Estatus del Viaje'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora de Salida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Entrega 🟡'), ('EN_RUTA', 'En Ruta / Tránsito 🚚'), ('ENTREGADA', 'Entregada al 100% 🟢'), ('PARCIAL', 'Entrega Parcial 🔵'), ('DEVUELTA', 'Rechazada / Devuelta 🔴'), ('NO_ATENDIDA', 'No Atendida (Desabasto) ⚫')], default='PENDIENTE', max_length=20, verbose_name='Estatus Logístico'),
        ),
        migrations.AlterField(
            model_name='remisionentrega',
            name='cantidad_entregada',
            field=models.IntegerField(verbose_name='Piezas Enviadas en este viaje'),
        ),
    ]
