# Generated by Django 6.0.2 on 2026-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0021_alter_remisionentrega_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensuministro',
            name='alerta_compras',
            field=models.BooleanField(default=False, help_text='Se activa si logística reporta desabasto.', verbose_name='🚨 Requiere Compra Urgente'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='evidencia_rechazo',
            field=models.FileField(blank=True, null=True, upload_to='logistica/rechazos/', verbose_name='Evidencia del Rechazo (Acta/Foto)'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='fecha_tentativa_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tentativa para el resto'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del Rechazo'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='sin_inventario',
            field=models.BooleanField(default=False, verbose_name='¿Sin inventario en Almacén?'),
        ),
        migrations.AddField(
            model_name='remisionentrega',
            name='solicitar_compras',
            field=models.BooleanField(default=False, help_text='Activa una alerta roja urgente en el panel principal.', verbose_name='Solicitar a Compras'),
        ),
        migrations.AlterField(
            model_name='remisionentrega',
            name='estatus_viaje',
            field=models.CharField(choices=[('EN_RUTA', '🚚 En Ruta hacia el Instituto'), ('ENTREGADA', '✅ Entregada y Comprobada'), ('PARCIAL', '🔵 Entrega Parcial (Faltan piezas)'), ('RECHAZO', '🔴 Rechazada por el Instituto')], default='EN_RUTA', max_length=20, verbose_name='Estatus del Viaje'),
        ),
    ]
