# Generated by Django 6.0.2 on 2026-04-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0022_ordensuministro_alerta_compras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordensuministro',
            name='alerta_compras',
        ),
        migrations.RemoveField(
            model_name='remisionentrega',
            name='fecha_tentativa_entrega',
        ),
        migrations.RemoveField(
            model_name='remisionentrega',
            name='sin_inventario',
        ),
        migrations.RemoveField(
            model_name='remisionentrega',
            name='solicitar_compras',
        ),
    ]
