# Generated by Django 6.0.2 on 2026-04-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0023_remove_ordensuministro_alerta_compras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Almacén')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Ubicación Físca')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': '🏢 Almacenes Físicos',
            },
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='folio_remision',
            field=models.CharField(default='S/F', help_text='Anota el número de ticket o factura.', max_length=100, verbose_name='Folio de Remisión / Factura'),
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='observaciones_calidad',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Calidad'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entradaalmacen',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licitaciones.almacen', verbose_name='Almacén Destino'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licitaciones.almacen', verbose_name='Almacén'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('almacen', 'medicamento', 'lote', 'fecha_caducidad')},
        ),
    ]
