# Generated by Django 6.0.2 on 2026-04-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0024_almacen_alter_entradaalmacen_folio_remision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoIntercompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_factura', models.CharField(help_text='Folio del documento fiscal que ampara este movimiento.', max_length=100, verbose_name='Folio de Orden / Factura Fiscal')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote Físico')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de Piezas')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='A cuánto se lo está vendiendo internamente.', max_digits=10, verbose_name='Precio Unitario Fiscal')),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Traspaso')),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador 📝 (No afecta inventario)'), ('COMPLETADO', 'Completado ✅ (Inventario movido)')], default='BORRADOR', max_length=20, verbose_name='Estado del Traspaso')),
                ('procesado', models.BooleanField(default=False, editable=False)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrada', to='licitaciones.almacen', verbose_name='Almacén Destino (El que Compra)')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salida', to='licitaciones.almacen', verbose_name='Almacén Origen (El que Vende)')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Clave a Transferir')),
            ],
            options={
                'verbose_name': 'Traspaso Interno',
                'verbose_name_plural': '🔄 Traspasos Inter-Compañías',
            },
        ),
    ]
