# Generated by Django 6.0.2 on 2026-04-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0025_traspasointercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaalmacen',
            name='acuse_recibo',
            field=models.FileField(blank=True, help_text='Sube el PDF o Foto del acuse firmado al recibir la mercancía.', null=True, upload_to='almacen/acuses/', verbose_name='Acuse de Recibo / Remisión Firmada'),
        ),
        migrations.AddField(
            model_name='entradaalmacen',
            name='factura_proveedor',
            field=models.FileField(blank=True, help_text='Sube la factura correspondiente a esta entrega.', null=True, upload_to='almacen/facturas/', verbose_name='Factura del Proveedor (PDF/XML)'),
        ),
    ]
