# Generated by Django 6.0.2 on 2026-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0026_entradaalmacen_acuse_recibo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensuministro',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Entrega Parcial'), ('ENTREGADA', 'Entregada'), ('DEVUELTA', 'Devuelta / Rechazada'), ('NO_ATENDIDA', 'No Atendida'), ('CANCELADA', 'Cancelada (Sin entrega)'), ('CANCELADA_EVIDENCIA', 'Cancelada (CON EVIDENCIA DE ENTREGA)')], default='PENDIENTE', max_length=20, verbose_name='Estatus Logístico'),
        ),
    ]
