# Generated by Django 6.0.2 on 2026-04-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0027_alter_ordensuministro_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('SAGO', 'Sago Medical'), ('GSM', 'GSM'), ('GAMS', 'GAMS')], max_length=20, unique=True)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(help_text='Usa la Contraseña de Aplicación de 16 letras', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correos',
            },
        ),
        migrations.AlterModelOptions(
            name='catalogomedicamento',
            options={'verbose_name': 'Clave', 'verbose_name_plural': 'Claves'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': '1. Contratos'},
        ),
    ]
