# Generated by Django 6.0.2 on 2026-04-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0028_configuracionemail_alter_catalogomedicamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Escanea aquí con la pistola de códigos', max_length=150, null=True, verbose_name='Código de Barras'),
        ),
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote Físico')),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', '📥 Entrada por Compra'), ('SALIDA_OPM', '📤 Salida por OPM'), ('TRASPASO_IN', '🔄 Entrada por Traspaso'), ('TRASPASO_OUT', '🔄 Salida por Traspaso'), ('MERMA', '❌ Merma / Caducidad'), ('AJUSTE', '⚙️ Ajuste Manual')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Movida')),
                ('saldo_restante', models.IntegerField(help_text='Cuántas piezas quedaron después de este movimiento', verbose_name='Saldo Posterior')),
                ('folio_documento', models.CharField(help_text='Ej. OC-123, REM-456, TRAS-789', max_length=100, verbose_name='Folio Relacionado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.almacen', verbose_name='Almacén')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Clave')),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': '📊 Kardex (Historial Exacto)',
                'ordering': ['-fecha'],
            },
        ),
    ]
