# Generated by Django 6.0.2 on 2026-04-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0029_inventario_codigo_barras_movimientokardex'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscanerKardex',
            fields=[
            ],
            options={
                'verbose_name': '📱 Escáner Kardex (Cámara)',
                'verbose_name_plural': '📱 Escáner Kardex (Cámara)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licitaciones.inventario',),
        ),
    ]
