# Generated by Django 6.0.2 on 2026-04-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0030_escanerkardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaalmacen',
            name='tipo_producto',
            field=models.CharField(choices=[('SECTORIZADO', 'Sectorizado (Sector Salud)'), ('COMERCIAL', 'Comercial')], default='COMERCIAL', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_producto',
            field=models.CharField(choices=[('SECTORIZADO', 'Sectorizado (Sector Salud)'), ('COMERCIAL', 'Comercial')], default='COMERCIAL', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='dependencia',
            field=models.CharField(blank=True, choices=[('IMSS_BIENESTAR', 'IMSS-Bienestar'), ('IMSS_ORDINARIO', 'IMSS Ordinario'), ('ISSSTE', 'ISSSTE'), ('SSA', 'Secretaría de Salud (SSA)'), ('SEDENA', 'SEDENA'), ('SEMAR', 'SEMAR'), ('OTRA', 'Otra Dependencia')], help_text='Selecciona la institución que solicitó esta orden.', max_length=50, null=True, verbose_name='Dependencia / Institución'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='servidor_correo',
            field=models.CharField(blank=True, default='smtp.resend.com', help_text='Ej: smtp.resend.com', max_length=100, null=True, verbose_name='Servidor SMTP'),
        ),
    ]
