# Generated by Django 6.0.2 on 2026-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0031_entradaalmacen_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correos_notificacion',
            field=models.TextField(blank=True, help_text='Escribe aquí los correos de los empleados para ESTA empresa, separados por coma.', null=True),
        ),
    ]
