# Generated by Django 6.0.2 on 2026-05-20 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0032_empresa_correos_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDirecto',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido Directo (10 días)',
                'verbose_name_plural': 'Pedidos Directos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licitaciones.ordensuministro',),
        ),
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes Físicos'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='entradaalmacen',
            options={'verbose_name': 'Entrada de Almacén', 'verbose_name_plural': 'Recepciones de Almacén'},
        ),
        migrations.AlterModelOptions(
            name='escanerkardex',
            options={'verbose_name': '📱 Escáner Kardex (Cámara)', 'verbose_name_plural': 'Escáner Kardex'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['fecha_caducidad'], 'verbose_name': 'Inventario Físico', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='movimientokardex',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Kardex', 'verbose_name_plural': 'Kardex (Historial Exacto)'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra (OC)'},
        ),
        migrations.AlterModelOptions(
            name='ordensuministro',
            options={'ordering': ['fecha_limite'], 'verbose_name': 'Orden de Suministro', 'verbose_name_plural': 'Órdenes de Suministro'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='remisionentrega',
            options={'verbose_name': 'Remisión Física', 'verbose_name_plural': 'Remisiones de Almacén'},
        ),
        migrations.AlterModelOptions(
            name='traspasointercompany',
            options={'verbose_name': 'Traspaso Interno', 'verbose_name_plural': 'Traspasos Inter-Compañías'},
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='clave_contrato',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='clave_medicamento_historico',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='descripcion_medicamento',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='numero_contrato_historico',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='numero_procedimiento_extra',
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='clavecontrato',
            name='piezas_historicas_entregadas',
            field=models.IntegerField(default=0, verbose_name='Histórico Entregado'),
        ),
        migrations.AddField(
            model_name='clavecontrato',
            name='piezas_historicas_solicitadas',
            field=models.IntegerField(default=0, verbose_name='Histórico Solicitado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='porcentaje_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 20.00 si se amplió el 20%', max_digits=5),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_convenio_modificatorio',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Convenio Modificatorio?'),
        ),
        migrations.AddField(
            model_name='entradaalmacen',
            name='piezas_rechazadas',
            field=models.PositiveIntegerField(default=0, help_text='Anota si llegaron cajas rotas, caducadas o diferentes.', verbose_name='Piezas Rechazadas (Mal estado)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='costo_administrativo',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Costo interno de procesamiento ($)', max_digits=8, verbose_name='Costo Administrativo de OC'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='es_compra_no_planeada',
            field=models.BooleanField(default=False, help_text='Marcar si es urgencia fuera de acuerdos/catálogos preaprobados.', verbose_name='Gasto Maverick (Fuera de Contrato)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_necesidad',
            field=models.DateField(default=django.utils.timezone.now, help_text='¿Cuándo se originó la necesidad interna?', verbose_name='Fecha de Solicitud (Necesidad)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_recepcion_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción Real'),
        ),
        migrations.AddField(
            model_name='ordensuministro',
            name='tipo_documento',
            field=models.CharField(choices=[('SUMINISTRO', 'Orden de Suministro (Gobierno)'), ('PEDIDO', 'Pedido Privado (Cliente)')], default='SUMINISTRO', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='partidacompra',
            name='piezas_rechazadas',
            field=models.PositiveIntegerField(default=0, help_text='Piezas devueltas por defecto del proveedor.', verbose_name='Pzas Rechazadas (Calidad)'),
        ),
        migrations.AddField(
            model_name='partidacompra',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Para medir el ahorro (PPV).', max_digits=12, verbose_name='Precio Presupuestado/Histórico'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dependencia',
            field=models.CharField(choices=[('HOSPITALES_GENERALES', [('HGM', 'Hospital General de México "Dr. Eduardo Liceaga"'), ('HGEA', 'Hospital General Dr. Manuel Gea González'), ('HJUAREZ', 'Hospital Juárez de México'), ('HJUAREZ_CENTRO', 'Hospital Juárez del Centro'), ('HMUJER', 'Hospital de la Mujer'), ('HHOMEOPATICO', 'Hospital Homeopático')]), ('INSTITUTOS_NACIONALES', [('INCAN', 'Instituto Nacional de Cancerología'), ('INCARDIO', 'Instituto Nacional de Cardiología Ignacio Chávez'), ('INCMNSZ', 'Instituto Nacional de Ciencias Médicas y Nutrición Salvador Zubirán'), ('INER', 'Instituto Nacional de Enfermedades Respiratorias'), ('INGER', 'Instituto Nacional de Geriatría'), ('INMEGEN', 'Instituto Nacional de Medicina Genómica'), ('INNN', 'Instituto Nacional de Neurología y Neurocirugía'), ('INP', 'Instituto Nacional de Pediatría'), ('INPER', 'Instituto Nacional de Perinatología'), ('INP_RAMON', 'Instituto Nacional de Psiquiatría Ramón de la Fuente'), ('INR', 'Instituto Nacional de Rehabilitación'), ('INSP', 'Instituto Nacional de Salud Pública'), ('HIMFG', 'Hospital Infantil de México Federico Gómez')]), ('INSTITUCIONES_FEDERALES', [('IMSS_BIENESTAR', 'IMSS-Bienestar'), ('IMSS_ORDINARIO', 'Instituto Mexicano del Seguro Social (IMSS)'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('SEMAR', 'Secretaría de Marina'), ('SEDENA', 'Secretaría de la Defensa Nacional'), ('CONASAMA', 'Comisión Nacional de Salud Mental y Adicciones'), ('CENAPRECE', 'Centro Nacional de Programas Preventivos y Control de Enfermedades'), ('CENSIDA', 'Centro Nacional para la Prevención y el Control del VIH y el SIDA'), ('BIRMEX', 'Laboratorios de Biológicos y Reactivos de México')]), ('HRAE_REGIONALES', [('HRAE_BAJIO', 'HRAE del Bajío'), ('HRAE_IXTAPALUCA', 'HRAE Ixtapaluca'), ('HRAE_VICTORIA', 'HRAE de Cd. Victoria'), ('HRAE_OAXACA', 'HRAE de Oaxaca'), ('HRAE_YUCATAN', 'HRAE de la Península de Yucatán'), ('HEP_CHIAPAS', 'Hospital de Especialidades Pediátricas Chiapas'), ('HRAE_CIUDAD_SALUD', 'Hospital Regional de Alta Especialidad Ciudad Salud')]), ('OTRA', 'Otra Dependencia')], max_length=100, verbose_name='Dependencia / Cliente'),
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='tipo_producto',
            field=models.CharField(choices=[('GENERICO_SEC', 'Genérico (Sectorizado)'), ('COMERCIAL_SEC', 'Comercial (Sectorizado)'), ('GENERICO', 'Genérico'), ('COMERCIAL', 'Comercial')], default='COMERCIAL', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_producto',
            field=models.CharField(choices=[('GENERICO_SEC', 'Genérico (Sectorizado)'), ('COMERCIAL_SEC', 'Comercial (Sectorizado)'), ('GENERICO', 'Genérico'), ('COMERCIAL', 'Comercial')], default='COMERCIAL', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='dependencia',
            field=models.CharField(choices=[('HOSPITALES_GENERALES', [('HGM', 'Hospital General de México "Dr. Eduardo Liceaga"'), ('HGEA', 'Hospital General Dr. Manuel Gea González'), ('HJUAREZ', 'Hospital Juárez de México'), ('HJUAREZ_CENTRO', 'Hospital Juárez del Centro'), ('HMUJER', 'Hospital de la Mujer'), ('HHOMEOPATICO', 'Hospital Homeopático')]), ('INSTITUTOS_NACIONALES', [('INCAN', 'Instituto Nacional de Cancerología'), ('INCARDIO', 'Instituto Nacional de Cardiología Ignacio Chávez'), ('INCMNSZ', 'Instituto Nacional de Ciencias Médicas y Nutrición Salvador Zubirán'), ('INER', 'Instituto Nacional de Enfermedades Respiratorias'), ('INGER', 'Instituto Nacional de Geriatría'), ('INMEGEN', 'Instituto Nacional de Medicina Genómica'), ('INNN', 'Instituto Nacional de Neurología y Neurocirugía'), ('INP', 'Instituto Nacional de Pediatría'), ('INPER', 'Instituto Nacional de Perinatología'), ('INP_RAMON', 'Instituto Nacional de Psiquiatría Ramón de la Fuente'), ('INR', 'Instituto Nacional de Rehabilitación'), ('INSP', 'Instituto Nacional de Salud Pública'), ('HIMFG', 'Hospital Infantil de México Federico Gómez')]), ('INSTITUCIONES_FEDERALES', [('IMSS_BIENESTAR', 'IMSS-Bienestar'), ('IMSS_ORDINARIO', 'Instituto Mexicano del Seguro Social (IMSS)'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('SEMAR', 'Secretaría de Marina'), ('SEDENA', 'Secretaría de la Defensa Nacional'), ('CONASAMA', 'Comisión Nacional de Salud Mental y Adicciones'), ('CENAPRECE', 'Centro Nacional de Programas Preventivos y Control de Enfermedades'), ('CENSIDA', 'Centro Nacional para la Prevención y el Control del VIH y el SIDA'), ('BIRMEX', 'Laboratorios de Biológicos y Reactivos de México')]), ('HRAE_REGIONALES', [('HRAE_BAJIO', 'HRAE del Bajío'), ('HRAE_IXTAPALUCA', 'HRAE Ixtapaluca'), ('HRAE_VICTORIA', 'HRAE de Cd. Victoria'), ('HRAE_OAXACA', 'HRAE de Oaxaca'), ('HRAE_YUCATAN', 'HRAE de la Península de Yucatán'), ('HEP_CHIAPAS', 'Hospital de Especialidades Pediátricas Chiapas'), ('HRAE_CIUDAD_SALUD', 'Hospital Regional de Alta Especialidad Ciudad Salud')]), ('OTRA', 'Otra Dependencia')], max_length=100, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_COMPRA', '📥 Entrada por Compra'), ('SALIDA_OPM', '📤 Salida por OPM'), ('ENTRADA_DEVOLUCION', '↩️ Entrada por Devolución (Rechazo)'), ('TRASPASO_IN', '🔄 Entrada por Traspaso'), ('TRASPASO_OUT', '🔄 Salida por Traspaso'), ('MERMA', '❌ Merma / Caducidad'), ('AJUSTE', '⚙️ Ajuste Manual')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='dependencia',
            field=models.CharField(blank=True, choices=[('HOSPITALES_GENERALES', [('HGM', 'Hospital General de México "Dr. Eduardo Liceaga"'), ('HGEA', 'Hospital General Dr. Manuel Gea González'), ('HJUAREZ', 'Hospital Juárez de México'), ('HJUAREZ_CENTRO', 'Hospital Juárez del Centro'), ('HMUJER', 'Hospital de la Mujer'), ('HHOMEOPATICO', 'Hospital Homeopático')]), ('INSTITUTOS_NACIONALES', [('INCAN', 'Instituto Nacional de Cancerología'), ('INCARDIO', 'Instituto Nacional de Cardiología Ignacio Chávez'), ('INCMNSZ', 'Instituto Nacional de Ciencias Médicas y Nutrición Salvador Zubirán'), ('INER', 'Instituto Nacional de Enfermedades Respiratorias'), ('INGER', 'Instituto Nacional de Geriatría'), ('INMEGEN', 'Instituto Nacional de Medicina Genómica'), ('INNN', 'Instituto Nacional de Neurología y Neurocirugía'), ('INP', 'Instituto Nacional de Pediatría'), ('INPER', 'Instituto Nacional de Perinatología'), ('INP_RAMON', 'Instituto Nacional de Psiquiatría Ramón de la Fuente'), ('INR', 'Instituto Nacional de Rehabilitación'), ('INSP', 'Instituto Nacional de Salud Pública'), ('HIMFG', 'Hospital Infantil de México Federico Gómez')]), ('INSTITUCIONES_FEDERALES', [('IMSS_BIENESTAR', 'IMSS-Bienestar'), ('IMSS_ORDINARIO', 'Instituto Mexicano del Seguro Social (IMSS)'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('SEMAR', 'Secretaría de Marina'), ('SEDENA', 'Secretaría de la Defensa Nacional'), ('CONASAMA', 'Comisión Nacional de Salud Mental y Adicciones'), ('CENAPRECE', 'Centro Nacional de Programas Preventivos y Control de Enfermedades'), ('CENSIDA', 'Centro Nacional para la Prevención y el Control del VIH y el SIDA'), ('BIRMEX', 'Laboratorios de Biológicos y Reactivos de México')]), ('HRAE_REGIONALES', [('HRAE_BAJIO', 'HRAE del Bajío'), ('HRAE_IXTAPALUCA', 'HRAE Ixtapaluca'), ('HRAE_VICTORIA', 'HRAE de Cd. Victoria'), ('HRAE_OAXACA', 'HRAE de Oaxaca'), ('HRAE_YUCATAN', 'HRAE de la Península de Yucatán'), ('HEP_CHIAPAS', 'Hospital de Especialidades Pediátricas Chiapas'), ('HRAE_CIUDAD_SALUD', 'Hospital Regional de Alta Especialidad Ciudad Salud')]), ('OTRA', 'Otra Dependencia')], max_length=100, null=True, verbose_name='Dependencia / Institución'),
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='numero_orden_suministro',
            field=models.CharField(max_length=150, verbose_name='Folio (No. Orden / Pedido)'),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimiento', models.CharField(choices=[('COTIZACION_PRIVADA', 'Cotización a Cliente Privado'), ('ADJUDICACION', 'Adjudicación Directa (Gobierno)'), ('INVESTIGACION', 'Investigación de Mercado (Gobierno)'), ('INVITACION_3', 'Invitación a 3 Personas (Gobierno)')], default='COTIZACION_PRIVADA', max_length=30, verbose_name='Tipo de Venta')),
                ('folio', models.CharField(blank=True, help_text='Déjalo en blanco para auto-generar el consecutivo (Ej: Sago.Cot-001).', max_length=50, unique=True, verbose_name='Folio de Cotización / Evento')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social (Cliente Privado)')),
                ('dependencia', models.CharField(blank=True, choices=[('HOSPITALES_GENERALES', [('HGM', 'Hospital General de México "Dr. Eduardo Liceaga"'), ('HGEA', 'Hospital General Dr. Manuel Gea González'), ('HJUAREZ', 'Hospital Juárez de México'), ('HJUAREZ_CENTRO', 'Hospital Juárez del Centro'), ('HMUJER', 'Hospital de la Mujer'), ('HHOMEOPATICO', 'Hospital Homeopático')]), ('INSTITUTOS_NACIONALES', [('INCAN', 'Instituto Nacional de Cancerología'), ('INCARDIO', 'Instituto Nacional de Cardiología Ignacio Chávez'), ('INCMNSZ', 'Instituto Nacional de Ciencias Médicas y Nutrición Salvador Zubirán'), ('INER', 'Instituto Nacional de Enfermedades Respiratorias'), ('INGER', 'Instituto Nacional de Geriatría'), ('INMEGEN', 'Instituto Nacional de Medicina Genómica'), ('INNN', 'Instituto Nacional de Neurología y Neurocirugía'), ('INP', 'Instituto Nacional de Pediatría'), ('INPER', 'Instituto Nacional de Perinatología'), ('INP_RAMON', 'Instituto Nacional de Psiquiatría Ramón de la Fuente'), ('INR', 'Instituto Nacional de Rehabilitación'), ('INSP', 'Instituto Nacional de Salud Pública'), ('HIMFG', 'Hospital Infantil de México Federico Gómez')]), ('INSTITUCIONES_FEDERALES', [('IMSS_BIENESTAR', 'IMSS-Bienestar'), ('IMSS_ORDINARIO', 'Instituto Mexicano del Seguro Social (IMSS)'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('SEMAR', 'Secretaría de Marina'), ('SEDENA', 'Secretaría de la Defensa Nacional'), ('CONASAMA', 'Comisión Nacional de Salud Mental y Adicciones'), ('CENAPRECE', 'Centro Nacional de Programas Preventivos y Control de Enfermedades'), ('CENSIDA', 'Centro Nacional para la Prevención y el Control del VIH y el SIDA'), ('BIRMEX', 'Laboratorios de Biológicos y Reactivos de México')]), ('HRAE_REGIONALES', [('HRAE_BAJIO', 'HRAE del Bajío'), ('HRAE_IXTAPALUCA', 'HRAE Ixtapaluca'), ('HRAE_VICTORIA', 'HRAE de Cd. Victoria'), ('HRAE_OAXACA', 'HRAE de Oaxaca'), ('HRAE_YUCATAN', 'HRAE de la Península de Yucatán'), ('HEP_CHIAPAS', 'Hospital de Especialidades Pediátricas Chiapas'), ('HRAE_CIUDAD_SALUD', 'Hospital Regional de Alta Especialidad Ciudad Salud')]), ('OTRA', 'Otra Dependencia')], max_length=100, null=True, verbose_name='Dependencia (Gobierno)')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('vigencia_dias', models.IntegerField(default=15, verbose_name='Días de Vigencia')),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador (En edición)'), ('ENVIADA', 'Enviada al Cliente / Dependencia'), ('GANADA', 'Ganada / Aprobada (Lista para Pedido)'), ('PERDIDA', 'Perdida / Rechazada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='Estatus Comercial')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.empresa', verbose_name='Empresa Emisora')),
            ],
            options={
                'verbose_name': 'Cotización / Venta Directa',
                'verbose_name_plural': 'Cotizaciones y Ventas Directas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote Afectado')),
                ('cantidad_afectada', models.PositiveIntegerField(verbose_name='Piezas Afectadas (Se restarán del stock)')),
                ('motivo', models.CharField(choices=[('PROXIMO_CADUCAR', '⏳ Próximo a Caducar'), ('VICIO_OCULTO', '🕵️\u200d♂️ Vicio Oculto / Defecto de Fábrica'), ('DANADO', '💥 Dañado en Almacén o Transporte')], max_length=20, verbose_name='Motivo del Problema')),
                ('resolucion', models.CharField(choices=[('EN_CUARENTENA', '🔒 En Cuarentena (Esperando decisión)'), ('DONATIVO', '🎁 Donativo (Salida sin cobro)'), ('DEVOLUCION', '🚚 Devolución a Proveedor (Garantía)'), ('DESTRUCCION', '🔥 Destrucción / Merma (Pérdida)')], default='EN_CUARENTENA', max_length=20, verbose_name='Decisión Final (Destino)')),
                ('genera_nota_credito', models.BooleanField(default=False, verbose_name='¿Genera Nota de Crédito a nuestro favor?')),
                ('monto_nota_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Nota de Crédito ($)')),
                ('aplica_penalizacion', models.BooleanField(default=False, verbose_name='¿Aplicar Multa/Penalización al Proveedor?')),
                ('monto_penalizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Penalización ($)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Detalles del defecto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('inventario_origen', models.ForeignKey(help_text='Selecciona el lote del inventario que vas a mandar a Cuarentena.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.inventario', verbose_name='Lote Original en Inventario')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Clave / Medicamento')),
                ('socio_comercial', models.ForeignKey(blank=True, help_text='¿A quién le vamos a reclamar?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.sociocomercial', verbose_name='Proveedor (Socio Comercial)')),
            ],
            options={
                'verbose_name': 'Control de Cuarentena y Merma',
                'verbose_name_plural': 'Cuarentenas y Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='PartidaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Solicitada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario Ofertado')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_cotizacion', to='licitaciones.cotizacion')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Medicamento (Catálogo Libre)')),
            ],
            options={
                'verbose_name': 'Partida Cotizada',
                'verbose_name_plural': 'Medicamentos Cotizados',
            },
        ),
        migrations.CreateModel(
            name='PartidaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Cant. Solicitada')),
                ('cantidad_entregada', models.IntegerField(default=0, verbose_name='Cant. Entregada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario')),
                ('clave_historica', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave Histórica')),
                ('clave_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licitaciones.clavecontrato', verbose_name='Clave del Medicamento')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licitaciones.catalogomedicamento', verbose_name='Catálogo Libre (Privados)')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='licitaciones.ordensuministro')),
            ],
            options={
                'verbose_name': 'Medicamento / Clave',
                'verbose_name_plural': 'Lista de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='PerfilEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(help_text='Ej: +5215540741751', max_length=20)),
                ('rol', models.CharField(choices=[('DIRECCION_GRAL', 'Dirección General'), ('DIRECCION_COMER', 'Dirección Comercial'), ('GERENCIA_COMERCIAL', 'Gerencia Comercial'), ('COORD_COMERCIAL', 'Coordinador Comercial'), ('ANALISTA_LICITA', 'Analista de Licitaciones'), ('ATENCION_COMERCIAL', 'Atención Comercial / Ventas'), ('ANALISTA_ATENCION', 'Analista Atención Comercial'), ('COMPRADOR', 'Ejecutivo de Compras'), ('GERENTE_LOGISTICA', 'Gerente de Logística'), ('AUX_ALMACEN', 'Auxiliar de Almacén / Chofer'), ('DIRECCION_ADMIN', 'Dirección Administrativa'), ('DIRECCION_COBR', 'Dirección Cobranza')], default='COORD_COMERCIAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
